# Generated by Django 4.1.2 on 2022-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('miesiac_urodzenia', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'osoba',
                'managed': True,
            },
        ),
    ]
