# Generated by Django 4.1.2 on 2022-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0002_alter_person_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='miesiac_urodzenia',
            field=models.DateTimeField(default='$0', verbose_name='data urodzenia'),
        ),
    ]
