# Generated by Django 4.1.2 on 2022-11-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0003_alter_person_miesiac_urodzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='miesiac_urodzenia',
        ),
    ]
