# Generated by Django 4.1.2 on 2022-11-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0004_remove_person_miesiac_urodzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='miesiac_urodzenia',
            field=models.CharField(choices=[('Styczeń', '1'), ('Luty', '2'), ('Marzec', '3'), ('Kwiecień', '4'), ('Maj', '5'), ('Czerwiec', '6'), ('Lipiec', '7'), ('Sierpień', '8'), ('Wrzesień', '9'), ('Październik', '10'), ('Listopad', '11'), ('Grudzień', '12')], default=0, max_length=11),
        ),
    ]
