# Generated by Django 4.1.2 on 2022-11-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0007_person_data_dodania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('kraj', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True, 'ordering': ['nazwisko']},
        ),
        migrations.AlterField(
            model_name='person',
            name='miesiac_urodzenia',
            field=models.IntegerField(choices=[(1, 'Styczen'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecien'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpien'), (9, 'Wrzesien'), (10, 'Pazdziernik'), (11, 'Listopad'), (12, 'Grudzien')], default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='person',
            name='druzyna',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='zajecia.team'),
        ),
    ]
