# Generated by Django 4.1.2 on 2022-11-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0010_alter_person_miesiac_urodzenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
