# Generated by Django 4.1.2 on 2022-11-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='druzyna',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='zajecia.team'),
        ),
    ]
